name = "NodeHarmonics"
uuid = "1096c90d-b118-4d86-93f2-11cef37dbdb7"
authors = ["Keith JL"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
